From c04533b08a3c0224fbb552d42095c1d2dc68198a Mon Sep 17 00:00:00 2001
From: Tiago de Paula Peixoto <tiago@skewed.de>
Date: Fri, 6 Jan 2017 22:18:05 +0000
Subject: [PATCH] Fix dlopen() flags problem with Python 3.6

---
 src/graph_tool/dl_import.py | 16 ++++++++++------
 1 file changed, 10 insertions(+), 6 deletions(-)

diff --git a/src/graph_tool/dl_import.py b/src/graph_tool/dl_import.py
index fd6c8e70..1d94f7ed 100644
--- a/src/graph_tool/dl_import.py
+++ b/src/graph_tool/dl_import.py
@@ -24,17 +24,21 @@ import sys
 import os.path
 
 try:
-    from DLFCN import RTLD_LAZY, RTLD_GLOBAL
+    from os import RTLD_LAZY, RTLD_GLOBAL
     dl_flags = RTLD_LAZY | RTLD_GLOBAL
 except ImportError:
-    # handle strange python installations, by importing from the deprecated dl
-    # module, otherwise from ctypes
     try:
-        from dl import RTLD_LAZY, RTLD_GLOBAL
+        from DLFCN import RTLD_LAZY, RTLD_GLOBAL
         dl_flags = RTLD_LAZY | RTLD_GLOBAL
     except ImportError:
-        from ctypes import RTLD_GLOBAL
-        dl_flags = RTLD_GLOBAL
+        # handle strange python installations, by importing from the deprecated dl
+        # module, otherwise from ctypes
+        try:
+            from dl import RTLD_LAZY, RTLD_GLOBAL
+            dl_flags = RTLD_LAZY | RTLD_GLOBAL
+        except ImportError:
+            from ctypes import RTLD_GLOBAL
+            dl_flags = RTLD_GLOBAL
 
 __all__ = ["dl_import"]
 
-- 
2.11.0

